-- insert a new person, get the autogenerated id, and use that to add to places
BEGIN TRANSACTION ;

insert into people(Name, Organization) values ("John", "Org2");

insert into places (someid, personid)
select 999, seq from sqlite_sequence where name="people";

COMMIT;
